### ISSUE TITLE
Invalid argument(s): Failed to load dynamic library 'phash.so': dlopen failed: cannot locate symbol "TIFFSetWarningHandler" referenced by "/data/app/~~dsq_8wJXYPiEvZhp0h9C8w==/com.example.tcg-n4L1yUnzT6xjvaZKt_iDZA==/lib/arm64/phash.so"...

### ISSUE THREAD

**Issue by ChurikiTenna** [aetilius/pHash#42]
I built phase.so as below:
```
export NDK_PATH=/Users/tenna/Library/Android/sdk/ndk/26.2.11394342
export ARCH=arm64-v8a
export TOOLCHAIN=$NDK_PATH/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android34-clang++

$TOOLCHAIN -shared -fPIC -o /Users/tenna/desktop/appname/android/app/src/main/jniLibs/$ARCH/phash.so \
    -I/Library/Frameworks/Mono.framework/Versions/6.12.0/include \
    -I/Users/tenna/pHash/CImg-3.3.5_pre03042417 \
    -L/Users/tenna/anaconda3/pkgs/jpeg-9e-h80987f9_1/lib \
    -L/Users/tenna/anaconda3/pkgs/libtiff-4.5.0-h313beb8_2/lib \
    -L/Users/tenna/anaconda3/pkgs/libpng-1.6.39-h80987f9_0/lib \
    /Users/tenna/pHash/src/pHash.cpp
```
Or
```
export NDK_PATH=/Users/tenna/Library/Android/sdk/ndk/26.2.11394342
export ARCH=arm64-v8a
export TOOLCHAIN=$NDK_PATH/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android34-clang++
$TOOLCHAIN -shared -fPIC -o /Users/tenna/desktop/app/android/app/src/main/jniLibs/$ARCH/phash.so \
    -I/Library/Frameworks/Mono.framework/Versions/6.12.0/include \
    -I/Users/tenna/pHash/third-party/CImg \
    -L/Library/Frameworks/Mono.framework/Versions/6.12.0/lib \
    /Users/tenna/pHash/src/pHash.cpp
```
When I try to open the phase.so file in flutter, it throws errors:
```
I/flutter ( 7373): getImagePhash.e Invalid argument(s): Failed to load dynamic library 'phash.so': dlopen failed: cannot locate symbol "TIFFSetWarningHandler" referenced by "/data/app/~~dsq_8wJXYPiEvZhp0h9C8w==/com.example.tcg-n4L1yUnzT6xjvaZKt_iDZA==/lib/arm64/phash.so"...
E/flutter ( 7373): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'phash.so': dlopen failed: cannot locate symbol "TIFFSetWarningHandler" referenced by "/data/app/~~dsq_8wJXYPiEvZhp0h9C8w==/com.example.tcg-n4L1yUnzT6xjvaZKt_iDZA==/lib/arm64/phash.so"...
E/flutter ( 7373): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter ( 7373): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter ( 7373): #2      lib (package:tcg/templates/hash2.dart:17:22)
E/flutter ( 7373): #3      lib (package:tcg/templates/hash2.dart)
E/flutter ( 7373): #4      calculateImageHash (package:tcg/templates/hash2.dart:23:39)
E/flutter ( 7373): #5      HashHelper2._computeImagePHash (package:tcg/templates/hash2.dart:90:16)
E/flutter ( 7373): #6      HashHelper2.getImagePhash (package:tcg/templates/hash2.dart:49:24)
E/flutter ( 7373): <asynchronous suspension>
E/flutter ( 7373): #7      _MyPageTabState.getdata (package:tcg/pages/my_page.dart:32:18)
E/flutter ( 7373): <asynchronous suspension>
E/flutter ( 7373): 
```
TIFFSetWarningHandler is supposed be imported from libtiff in CImg.h.

I tried reinstalling libtiff.dylib through homebrew which did not solve the problem.
This made me suspect that the version of libtiff installed may differ from the version required for the library.
But I could not find any specification either.

**Comment by aetilius** [comment]
The symbol `TIFFSetWarningHandler` is from `libtiff`. Your NDK build is producing `phash.so` with an unresolved reference to that symbol because libtiff isn't being linked into the final shared object -- the `-L` paths you have are just paths, not actual link commands. You need `-ltiff -lpng -ljpeg -lz` (and probably `-lpthread -lm`) at the end of the link line.

A minimal fix to your invocation:

```sh
$TOOLCHAIN -shared -fPIC -o phash.so \
    -I.../CImg-3.3.5_pre03042417 \
    -L$ANACONDA_LIB \
    pHash.cpp \
    -ltiff -lpng -ljpeg -lz -lm
```

That said: linking Anaconda-built x86_64 macOS libs (`/Users/tenna/anaconda3/pkgs/...`) into an Android arm64 shared object isn't going to work in general -- those libs are the wrong OS *and* arch. You'd need NDK-built versions of libtiff/libpng/libjpeg, ideally cross-compiled with the same NDK toolchain.

Closing this since it's an Android-build invocation issue, not a pHash bug. If you'd like a worked Android NDK CMakeLists for cross-compiling libpHash, that could be a separate feature request (Android isn't currently a supported target in this repo).
